# Generated by Django 3.0.5 on 2020-05-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='sectors',
            new_name='_activity_sectors',
        ),
    ]
