# Generated by Django 3.0.5 on 2020-04-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='pdf_name',
        ),
    ]
