# Generated by Django 3.0.5 on 2020-05-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='text_tokens',
            field=models.TextField(default='', help_text='Tokens du texte de la phrase, sous forme de string et séparé par des pipe |', verbose_name='Tokens'),
            preserve_default=False,
        ),
    ]
