# Generated by Django 3.0.5 on 2020-05-07 12:18

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200504_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpef',
            name='file_object',
            field=models.FileField(help_text='Document DPEF ou DDR au format PDF.', unique=True, upload_to='polls/models/dpef/', validators=[polls.models._validate_file_extension], verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='vector',
            field=polls.models.Vector(default='[]'),
        ),
    ]
