# Generated by Django 3.0.5 on 2020-06-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200607_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='_weight',
            field=models.FloatField(help_text='Poids de la phrase, donnée par le poids BM25 de ses constituants.', null=True, verbose_name='Weight'),
        ),
    ]
