# Generated by Django 3.0.5 on 2020-05-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200507_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='vector',
        ),
        migrations.AddField(
            model_name='sentence',
            name='_vector',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
