# Generated by Django 3.0.5 on 2020-06-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200607_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='embedding_vector',
            new_name='_embedding_vector',
        ),
    ]
